[package]
name = "float-lerp"
version = "0.2.0"
edition = "2021"
description = "Lerp and InverseLerp functions for floats"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = { version = "0.2" }